### PR TITLE
build CKEditor5 simply with basic function that compatible with CKEditor4

### PR DESCRIPTION
**Pull request by WebberMao**
Hello, this PR done the following  jobs

1. build CKEditor5 simply with basic function that compatible with CKEditor4.
2. create Ckeditor5 ckfinder.
3. fix Ckeditor4 file_uploader can not be use in 'basic' pkg_type bug.

The user can switch the version of CKEditor by setting 
`app = CKEditor(app, version=4) #version=4 in default` 
`app = CKEditor(app, version=5)`

and change the editor_type (support CKEditor5 only) by setting config 
`CKEDITOR_EDITOR_TYPE = 'classic' #and all the other types`

hope you will like it!

### CODE REVIEW

**Comment by abdounasser202** [comment]
I read the issue #39 and i'm asking, what's the status of this PR please ?

**Comment by greyli** [comment]
> what's the status of this PR please?

@abdounasser202  I'm thinking of providing a separate class for CKEditor 5 (something like https://github.com/greyli/bootstrap-flask/pull/161), so that we don't need to set a default value for `version` when creating the extension class.

@WebberMao Thanks for working on this. Could you refactor to use different extension classes for different versions? By the way, I notice you rewrite the whole file, it makes git can't diff the changes.

**Comment by WebberMao** [comment]
@greyli Sure, it may take some time. I will post another RP later.

**Comment by greyli** [comment]
Thank you, there is no hurry. Please also use separate PRs for different tasks.

**Pull request closed without merging**
